### ISSUE TITLE
Please add OSX binary

### ISSUE THREAD

**Issue by wowcut** [titpetric/pendulum#1]
A binary for OSX would be great. Thanks!

**Comment by titpetric** [comment]
Do you have a GOOS/GOARCH combination which you'd like me to add? I suspect GOOS=darwin, but I haven't got an OSX to check the GOARCH. There's at least two, no?

**Comment by titpetric** [comment]
Added darwin with amd64 and 386. Most likely you'll use the amd one. Apparently there's also arm GOOS'es which I'm not supporting at this point for this architecture, but I might add an arm version for Raspberry PIs...

I'm closing the issue, since I think this should resolve it for you. Grab an executable from the releases page :) BR
